### ISSUE TITLE
The action doesn't work as intended

### ISSUE THREAD

**Issue by hkrsmk** [hkrsmk/ghost-update-action#1]
I think the issue is here:
https://github.com/TryGhost/Ghost-CLI/blob/08943e54b27361b45360ab65c2e81803f7a122c5/packages/ghost-cli/lib/ui/index.js#L147

Have seen it happen for all sudo-less ghost cli commands

Things tried:
- playing around with environment variables and storing the entire command string as a secret
- removing the ! point in the CLI code (but it just times out instead, without actually working

error logs:
```
/usr/bin/docker run --name e1cc5168b80a63d33a4afdbb175df92ee67b17_4d959d --label e1cc51 --workdir /github/workspace --rm -e GHOST_VERSION -e INPUT_HOST -e INPUT_USERNAME -e INPUT_PASSWORD -e INPUT_PORT -e INPUT_SCRIPT -e INPUT_PASSPHRASE -e INPUT_SYNC -e INPUT_USE_INSECURE_CIPHER -e INPUT_CIPHER -e INPUT_TIMEOUT -e INPUT_COMMAND_TIMEOUT -e INPUT_KEY -e INPUT_KEY_PATH -e INPUT_FINGERPRINT -e INPUT_PROXY_HOST -e INPUT_PROXY_PORT -e INPUT_PROXY_USERNAME -e INPUT_PROXY_PASSWORD -e INPUT_PROXY_PASSPHRASE -e INPUT_PROXY_TIMEOUT -e INPUT_PROXY_KEY -e INPUT_PROXY_KEY_PATH -e INPUT_PROXY_FINGERPRINT -e INPUT_PROXY_CIPHER -e INPUT_PROXY_USE_INSECURE_CIPHER -e INPUT_SCRIPT_STOP -e INPUT_ENVS -e INPUT_DEBUG -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e RUNNER_OS -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/adv/adv":"/github/workspace" e1cc51:68b80a63d33a4afdbb175df92ee67b17
======CMD======
cd ***
ghost update $GHOST_VERSION

======END======
out: - Inspecting operating system
out: - Checking for deprecations
out: [16:38:27] Checking for Ghost-CLI updates [started]
out: [16:38:27] Checking for Ghost-CLI updates [completed]
out: [16:38:27] Ensuring correct ~/.config folder ownership [started]
out: [16:38:27] Ensuring correct ~/.config folder ownership [completed]
out: + sudo systemctl is-active ghost_adventgineering-org
err: /usr/lib/node_modules/ghost-cli/lib/ui/index.js:148
err:             throw new errors.SystemError('Prompts have been disabled, all options must be provided via command line flags');
err:             ^
err: 
err: SystemError: Prompts have been disabled, all options must be provided via command line flags
err:     at UI.prompt (/usr/lib/node_modules/ghost-cli/lib/ui/index.js:148:19)
err:     at Socket.<anonymous> (/usr/lib/node_modules/ghost-cli/lib/ui/index.js:248:***)
err:     at Socket.emit (events.js:412:35)
err:     at addChunk (internal/streams/readable.js:293:12)
err:     at readableAddChunk (internal/streams/readable.js:267:9)
err:     at Socket.Readable.push (internal/streams/readable.js:206:10)
err:     at Pipe.onStreamRead (internal/stream_base_commons.js:188:23) {
err:   options: {
err:     message: 'Prompts have been disabled, all options must be provided via command line flags'
err:   },
err:   logMessageOnly: undefined,
err:   help: 'You can always refer to https://ghost.org/docs/ghost-cli/ for troubleshooting.',
err:   err: {}
err: }
2021/09/30 16:38:28 Process exited with status 1
```

**Comment by hkrsmk** [comment]
Might have to move away from appleboy's script to fix this issue. Not sure.
